from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
from reportlab.pdfgen import canvas
from datetime import datetime
from typing import Dict
import os


class PDFService:
    """Service for generating PDF reports"""
    
    def __init__(self):
        self.output_dir = "app/static/pdfs"
        os.makedirs(self.output_dir, exist_ok=True)
        
        # Professional color palette with high contrast
        self.colors = {
            'primary': colors.HexColor('#1E40AF'),      # Deep Blue
            'primary_light': colors.HexColor('#3B82F6'), # Light Blue
            'secondary': colors.HexColor('#0F172A'),    # Dark Navy
            'accent': colors.HexColor('#6366F1'),       # Indigo
            'success': colors.HexColor('#059669'),      # Green
            'warning': colors.HexColor('#D97706'),      # Amber
            'danger': colors.HexColor('#DC2626'),       # Red
            'gray_dark': colors.HexColor('#374151'),    # Dark Gray
            'gray_medium': colors.HexColor('#6B7280'),  # Medium Gray
            'gray_light': colors.HexColor('#F3F4F6'),   # Light Gray
            'white': colors.white,
            'bg_blue': colors.HexColor('#EFF6FF'),      # Light Blue BG
            'bg_green': colors.HexColor('#ECFDF5'),     # Light Green BG
            'bg_yellow': colors.HexColor('#FFFBEB'),    # Light Yellow BG
            'bg_red': colors.HexColor('#FEF2F2'),       # Light Red BG
        }
    
    def _add_page_number(self, canvas, doc):
        """Add page numbers and footer to each page"""
        canvas.saveState()
        
        # Footer line
        canvas.setStrokeColor(self.colors['gray_light'])
        canvas.setLineWidth(1)
        canvas.line(50, 50, A4[0] - 50, 50)
        
        # Page number
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(self.colors['gray_medium'])
        canvas.drawRightString(A4[0] - 50, 35, text)
        
        # Footer text
        canvas.setFillColor(self.colors['gray_medium'])
        canvas.drawString(50, 35, "Generated by WebAnalyzer AI")
        
        # Website URL on right
        canvas.setFillColor(self.colors['primary'])
        canvas.drawRightString(A4[0] - 50, 20, "www.webanalyzer.ai")
        
        canvas.restoreState()
    
    async def generate_report(self, analysis_data: Dict) -> str:
        """Generate PDF report from analysis data"""
        try:
            filename = f"analysis_{analysis_data['id']}.pdf"
            output_path = os.path.join(self.output_dir, filename)
            
            print(f"📄 Creating enhanced PDF at: {output_path}")
            
            doc = SimpleDocTemplate(
                output_path,
                pagesize=A4,
                rightMargin=50,
                leftMargin=50,
                topMargin=60,
                bottomMargin=70
            )
            
            elements = []
            styles = getSampleStyleSheet()
            
            # Custom styles with better contrast
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=32,
                textColor=self.colors['white'],
                spaceAfter=10,
                alignment=TA_CENTER,
                fontName='Helvetica-Bold',
                leading=38
            )
            
            subtitle_style = ParagraphStyle(
                'Subtitle',
                parent=styles['Normal'],
                fontSize=11,
                textColor=self.colors['gray_dark'],
                alignment=TA_CENTER,
                spaceAfter=5,
                fontName='Helvetica'
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=20,
                textColor=self.colors['primary'],
                spaceAfter=15,
                spaceBefore=20,
                fontName='Helvetica-Bold'
            )
            
            subheading_style = ParagraphStyle(
                'CustomSubHeading',
                parent=styles['Heading3'],
                fontSize=14,
                textColor=self.colors['secondary'],
                spaceAfter=10,
                spaceBefore=12,
                fontName='Helvetica-Bold'
            )
            
            normal_style = ParagraphStyle(
                'CustomNormal',
                parent=styles['Normal'],
                fontSize=10,
                leading=16,
                alignment=TA_LEFT,
                textColor=self.colors['gray_dark'],
                fontName='Helvetica'
            )
            
            bullet_style = ParagraphStyle(
                'BulletStyle',
                parent=normal_style,
                leftIndent=20,
                bulletIndent=10,
                spaceAfter=6
            )
            
            # Header
            header_data = [[Paragraph("WEBSITE ANALYSIS REPORT", title_style)]]
            header_table = Table(header_data, colWidths=[A4[0] - 100])
            header_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), self.colors['primary']),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('TOPPADDING', (0, 0), (-1, -1), 25),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 25),
                ('ROUNDEDCORNERS', [12, 12, 12, 12])
            ]))
            elements.append(header_table)
            elements.append(Spacer(1, 0.25*inch))
            
            # Website info
            info_data = [[
                Paragraph(f"<b>Website:</b> {analysis_data.get('website_url', '')}", subtitle_style),
                Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", subtitle_style)
            ]]
            info_table = Table(info_data, colWidths=[3.5*inch, 3*inch])
            info_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), self.colors['bg_blue']),
                ('ALIGN', (0, 0), (0, 0), 'LEFT'),
                ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
                ('TOPPADDING', (0, 0), (-1, -1), 12),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('LEFTPADDING', (0, 0), (-1, -1), 15),
                ('RIGHTPADDING', (0, 0), (-1, -1), 15),
                ('ROUNDEDCORNERS', [8, 8, 8, 8])
            ]))
            elements.append(info_table)
            elements.append(Spacer(1, 0.35*inch))
            
            # Overall Score
            overall_score = analysis_data.get('overall_score', 0)
            score_color = self._get_score_color(overall_score)
            
            score_data = [
                [Paragraph(f'<font size="56" color="{score_color}"><b>{overall_score:.0f}</b></font>', 
                         ParagraphStyle('ScoreStyle', alignment=TA_CENTER))],
                [Paragraph('<font size="13" color="#6B7280"><b>Overall Score</b></font>', 
                         ParagraphStyle('ScoreLabelStyle', alignment=TA_CENTER))]
            ]
            
            score_table = Table(score_data, colWidths=[2.2*inch], rowHeights=[1*inch, 0.35*inch])
            score_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), self.colors['white']),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('BOX', (0, 0), (-1, -1), 3, colors.HexColor(score_color)),
                ('ROUNDEDCORNERS', [15, 15, 15, 15]),
                ('TOPPADDING', (0, 0), (-1, -1), 15),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 15)
            ]))
            
            score_wrapper = Table([[score_table]], colWidths=[A4[0] - 100])
            score_wrapper.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE')
            ]))
            elements.append(score_wrapper)
            elements.append(Spacer(1, 0.35*inch))
            
            # Score Breakdown
            ux_score = analysis_data.get('ux_analysis', {}).get('score', 0)
            seo_score = analysis_data.get('seo_analysis', {}).get('score', 0)
            perf_score = analysis_data.get('performance_analysis', {}).get('score', 0)
            content_score = analysis_data.get('content_analysis', {}).get('score', 0)
            
            score_breakdown = [
                [
                    Paragraph('<b>UX Score</b>', ParagraphStyle('', fontSize=11, alignment=TA_CENTER, textColor=self.colors['gray_dark'])),
                    Paragraph('<b>SEO Score</b>', ParagraphStyle('', fontSize=11, alignment=TA_CENTER, textColor=self.colors['gray_dark'])),
                    Paragraph('<b>Performance</b>', ParagraphStyle('', fontSize=11, alignment=TA_CENTER, textColor=self.colors['gray_dark'])),
                    Paragraph('<b>Content</b>', ParagraphStyle('', fontSize=11, alignment=TA_CENTER, textColor=self.colors['gray_dark']))
                ],
                [
                    Paragraph(f'<font size="28" color="{self._get_score_color(ux_score)}"><b>{ux_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="28" color="{self._get_score_color(seo_score)}"><b>{seo_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="28" color="{self._get_score_color(perf_score)}"><b>{perf_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="28" color="{self._get_score_color(content_score)}"><b>{content_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER))
                ]
            ]
            
            breakdown_table = Table(score_breakdown, colWidths=[1.5*inch] * 4, rowHeights=[0.35*inch, 0.7*inch])
            breakdown_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.colors['white']),
                ('BACKGROUND', (0, 1), (0, 1), self.colors['bg_blue']),
                ('BACKGROUND', (1, 1), (1, 1), self.colors['bg_green']),
                ('BACKGROUND', (2, 1), (2, 1), self.colors['bg_yellow']),
                ('BACKGROUND', (3, 1), (3, 1), self.colors['bg_red']),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                ('TOPPADDING', (0, 1), (-1, -1), 15),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 15),
                ('BOX', (0, 0), (-1, -1), 1.5, self.colors['gray_light']),
                ('INNERGRID', (0, 0), (-1, -1), 1.5, self.colors['white']),
                ('ROUNDEDCORNERS', [10, 10, 10, 10])
            ]))
            
            elements.append(breakdown_table)
            elements.append(Spacer(1, 0.4*inch))
            
            # Executive Summary
            elements.append(Paragraph("📊 Executive Summary", heading_style))
            elements.append(HRFlowable(width="100%", thickness=2, color=self.colors['primary_light'], spaceBefore=5, spaceAfter=15))
            
            summary_text = analysis_data.get('ai_summary', 'No summary available')
            summary_text = summary_text.replace('**', '').replace('##', '').replace('###', '').replace('*', '')
            
            for para in summary_text.split('\n\n'):
                if para.strip():
                    elements.append(Paragraph(para.strip(), normal_style))
                    elements.append(Spacer(1, 0.12*inch))
            
            elements.append(Spacer(1, 0.25*inch))
            
            # Priority Recommendations
            elements.append(Paragraph("🎯 Priority Recommendations", heading_style))
            elements.append(HRFlowable(width="100%", thickness=2, color=self.colors['primary_light'], spaceBefore=5, spaceAfter=15))
            
            recommendations = analysis_data.get('priority_recommendations', [])
            
            if recommendations:
                for i, rec in enumerate(recommendations[:5], 1):
                    priority_colors = {
                        'High': (self.colors['danger'], self.colors['bg_red']),
                        'Medium': (self.colors['warning'], self.colors['bg_yellow']),
                        'Low': (self.colors['success'], self.colors['bg_green'])
                    }
                    border_color, bg_color = priority_colors.get(rec.get('priority', 'N/A'), (self.colors['gray_medium'], self.colors['gray_light']))
                    
                    rec_content = [
                        [Paragraph(f'<b>{i}. {rec.get("title", "")}</b>', 
                                  ParagraphStyle('RecTitle', fontSize=13, textColor=self.colors['secondary'], fontName='Helvetica-Bold'))],
                        [Paragraph(rec.get('description', ''), normal_style)],
                        [Paragraph(f'<font size="9" color="#6B7280"><b>Priority:</b> {rec.get("priority", "N/A")} | <b>Impact:</b> {rec.get("impact", "N/A")} | <b>Effort:</b> {rec.get("effort", "N/A")}</font>', 
                                  ParagraphStyle('RecMeta'))]
                    ]
                    
                    rec_table = Table(rec_content, colWidths=[A4[0] - 120])
                    rec_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, -1), bg_color),
                        ('LEFTPADDING', (0, 0), (-1, -1), 15),
                        ('RIGHTPADDING', (0, 0), (-1, -1), 15),
                        ('TOPPADDING', (0, 0), (-1, -1), 12),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                        ('LINEABOVE', (0, 0), (-1, 0), 4, border_color),
                        ('ROUNDEDCORNERS', [8, 8, 8, 8])
                    ]))
                    
                    elements.append(rec_table)
                    elements.append(Spacer(1, 0.18*inch))
            
            elements.append(PageBreak())
            
            # Detailed Analysis Sections
            sections = [
                ('🎨 UX Analysis', 'ux_analysis', self.colors['primary'], self.colors['bg_blue']),
                ('🔍 SEO Analysis', 'seo_analysis', self.colors['success'], self.colors['bg_green']),
                ('⚡ Performance Analysis', 'performance_analysis', self.colors['warning'], self.colors['bg_yellow']),
                ('📝 Content Analysis', 'content_analysis', self.colors['danger'], self.colors['bg_red'])
            ]
            
            for section_title, section_key, section_color, section_bg in sections:
                section_data = analysis_data.get(section_key, {})
                score = section_data.get('score', 0)
                
                elements.append(Paragraph(section_title, ParagraphStyle('SectionHeading', parent=heading_style, textColor=section_color)))
                elements.append(HRFlowable(width="100%", thickness=2, color=section_color, spaceBefore=5, spaceAfter=10))
                elements.append(Paragraph(f'<b>Score: <font color="{self._get_score_color(score)}">{score:.0f}/100</font></b>', 
                                        ParagraphStyle('ScoreBadge', fontSize=12, textColor=self.colors['gray_dark'])))
                elements.append(Spacer(1, 0.15*inch))
                
                elements.append(Paragraph("<b>⚠️ Issues Found:</b>", subheading_style))
                issues = section_data.get('issues', [])
                if issues:
                    for issue in issues[:10]:
                        elements.append(Paragraph(f'• {issue}', bullet_style))
                else:
                    elements.append(Paragraph("✓ No issues found", 
                                            ParagraphStyle('NoIssues', parent=normal_style, textColor=self.colors['success'])))
                
                elements.append(Spacer(1, 0.18*inch))
                elements.append(Paragraph("<b>💡 Recommendations:</b>", subheading_style))
                
                recs = section_data.get('recommendations', [])
                if recs:
                    for rec in recs[:10]:
                        elements.append(Paragraph(f'• {rec}', bullet_style))
                else:
                    elements.append(Paragraph("No recommendations", normal_style))
                
                elements.append(Spacer(1, 0.35*inch))
            
            print(f"📄 Building PDF document...")
            doc.build(elements, onFirstPage=self._add_page_number, onLaterPages=self._add_page_number)
            print(f"✅ PDF created successfully: {output_path}")
            
            return output_path
            
        except Exception as e:
            print(f"❌ PDF generation failed: {e}")
            import traceback
            traceback.print_exc()
            raise
    
    def _get_score_color(self, score: float) -> str:
        """Get color based on score with high contrast"""
        if score >= 80:
            return '#059669'  # Green
        elif score >= 60:
            return '#D97706'  # Amber
        elif score >= 40:
            return '#F59E0B'  # Orange
        else:
            return '#DC2626'  # Red
