from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
from reportlab.pdfgen import canvas
from datetime import datetime
from typing import Dict
import os


class PDFService:
    """Service for generating PDF reports"""
    
    def __init__(self):
        self.output_dir = "app/static/pdfs"
        os.makedirs(self.output_dir, exist_ok=True)
    
    def _add_page_number(self, canvas, doc):
        """Add page numbers and footer to each page"""
        canvas.saveState()
        
        # Footer line
        canvas.setStrokeColor(colors.HexColor('#E5E7EB'))
        canvas.setLineWidth(1)
        canvas.line(50, 50, A4[0] - 50, 50)
        
        # Page number
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(colors.HexColor('#6B7280'))
        canvas.drawRightString(A4[0] - 50, 35, text)
        
        # Footer text
        canvas.drawString(50, 35, "Generated by WebAnalyzer AI")
        
        canvas.restoreState()
    
    async def generate_report(self, analysis_data: Dict) -> str:
        """
        Generate PDF report from analysis data
        
        Args:
            analysis_data: Complete analysis data
            
        Returns:
            Path to generated PDF file
        """
        try:
            # Generate PDF filename
            filename = f"analysis_{analysis_data['id']}.pdf"
            output_path = os.path.join(self.output_dir, filename)
            
            print(f"📄 Creating PDF at: {output_path}")
            
            # Create PDF document
            doc = SimpleDocTemplate(
                output_path,
                pagesize=A4,
                rightMargin=50,
                leftMargin=50,
                topMargin=60,
                bottomMargin=70
            )
            
            # Container for the 'Flowable' objects
            elements = []
            
            # Define styles
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=28,
                textColor=colors.HexColor('#1E40AF'),
                spaceAfter=10,
                alignment=TA_CENTER,
                fontName='Helvetica-Bold',
                leading=34
            )
            
            subtitle_style = ParagraphStyle(
                'Subtitle',
                parent=styles['Normal'],
                fontSize=12,
                textColor=colors.HexColor('#6B7280'),
                alignment=TA_CENTER,
                spaceAfter=5
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=18,
                textColor=colors.HexColor('#2563EB'),
                spaceAfter=15,
                spaceBefore=20,
                fontName='Helvetica-Bold',
                borderWidth=0,
                borderColor=colors.HexColor('#2563EB'),
                borderPadding=5,
                backColor=colors.HexColor('#EFF6FF'),
                leftIndent=10,
                rightIndent=10
            )
            
            subheading_style = ParagraphStyle(
                'CustomSubHeading',
                parent=styles['Heading3'],
                fontSize=13,
                textColor=colors.HexColor('#1F2937'),
                spaceAfter=10,
                spaceBefore=12,
                fontName='Helvetica-Bold'
            )
            
            normal_style = ParagraphStyle(
                'CustomNormal',
                parent=styles['Normal'],
                fontSize=10,
                leading=16,
                alignment=TA_LEFT,
                textColor=colors.HexColor('#374151')
            )
            
            bullet_style = ParagraphStyle(
                'BulletStyle',
                parent=normal_style,
                leftIndent=20,
                bulletIndent=10,
                spaceAfter=6
            )
            
            # Header with gradient effect (simulated with colored box)
            header_data = [[Paragraph("WEBSITE ANALYSIS REPORT", title_style)]]
            header_table = Table(header_data, colWidths=[A4[0] - 100])
            header_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#2563EB')),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('TOPPADDING', (0, 0), (-1, -1), 20),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 20),
                ('ROUNDEDCORNERS', [10, 10, 10, 10])
            ]))
            elements.append(header_table)
            elements.append(Spacer(1, 0.2*inch))
            
            # Website URL and Date
            elements.append(Paragraph(f"<b>Website:</b> {analysis_data.get('website_url', '')}", subtitle_style))
            elements.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", subtitle_style))
            elements.append(Spacer(1, 0.3*inch))
            
            # Overall Score - Large centered box
            overall_score = analysis_data.get('overall_score', 0)
            score_color = self._get_score_color(overall_score)
            
            score_data = [
                [Paragraph(f'<font size="48" color="{score_color}"><b>{overall_score:.0f}</b></font>', 
                         ParagraphStyle('ScoreStyle', alignment=TA_CENTER))],
                [Paragraph('<font size="12" color="#6B7280">Overall Score</font>', 
                         ParagraphStyle('ScoreLabelStyle', alignment=TA_CENTER))]
            ]
            
            score_table = Table(score_data, colWidths=[2*inch], rowHeights=[0.8*inch, 0.3*inch])
            score_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F9FAFB')),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('BOX', (0, 0), (-1, -1), 2, colors.HexColor(score_color)),
                ('ROUNDEDCORNERS', [15, 15, 15, 15]),
                ('TOPPADDING', (0, 0), (-1, -1), 15),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 15)
            ]))
            
            # Center the score table
            score_wrapper = Table([[score_table]], colWidths=[A4[0] - 100])
            score_wrapper.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE')
            ]))
            elements.append(score_wrapper)
            elements.append(Spacer(1, 0.3*inch))
            
            # Score Breakdown - Colorful cards
            ux_score = analysis_data.get('ux_analysis', {}).get('score', 0)
            seo_score = analysis_data.get('seo_analysis', {}).get('score', 0)
            perf_score = analysis_data.get('performance_analysis', {}).get('score', 0)
            content_score = analysis_data.get('content_analysis', {}).get('score', 0)
            
            score_breakdown = [
                ['UX Score', 'SEO Score', 'Performance', 'Content'],
                [
                    Paragraph(f'<font size="24" color="{self._get_score_color(ux_score)}"><b>{ux_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="24" color="{self._get_score_color(seo_score)}"><b>{seo_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="24" color="{self._get_score_color(perf_score)}"><b>{perf_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="24" color="{self._get_score_color(content_score)}"><b>{content_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER))
                ]
            ]
            
            breakdown_table = Table(score_breakdown, colWidths=[1.2*inch] * 4)
            breakdown_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F3F4F6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1F2937')),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('TOPPADDING', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('TOPPADDING', (0, 1), (-1, -1), 15),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 15),
                ('BACKGROUND', (0, 1), (0, 1), colors.HexColor('#EFF6FF')),
                ('BACKGROUND', (1, 1), (1, 1), colors.HexColor('#F0FDF4')),
                ('BACKGROUND', (2, 1), (2, 1), colors.HexColor('#FEF3C7')),
                ('BACKGROUND', (3, 1), (3, 1), colors.HexColor('#FEE2E2')),
                ('GRID', (0, 0), (-1, -1), 1, colors.white),
                ('ROUNDEDCORNERS', [10, 10, 10, 10])
            ]))
            
            elements.append(breakdown_table)
            elements.append(Spacer(1, 0.4*inch))
            
            # Executive Summary with styled box
            elements.append(Paragraph("📊 Executive Summary", heading_style))
            summary_text = analysis_data.get('ai_summary', 'No summary available')
            summary_text = summary_text.replace('**', '').replace('##', '').replace('###', '').replace('*', '')
            
            paragraphs = summary_text.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    elements.append(Paragraph(para.strip(), normal_style))
                    elements.append(Spacer(1, 0.1*inch))
            
            elements.append(Spacer(1, 0.2*inch))
            
            # Priority Recommendations with colored boxes
            elements.append(Paragraph("🎯 Priority Recommendations", heading_style))
            recommendations = analysis_data.get('priority_recommendations', [])
            
            if recommendations:
                for i, rec in enumerate(recommendations[:5], 1):
                    rec_title = rec.get('title', 'Recommendation')
                    rec_desc = rec.get('description', '')
                    rec_priority = rec.get('priority', 'N/A')
                    rec_impact = rec.get('impact', 'N/A')
                    rec_effort = rec.get('effort', 'N/A')
                    
                    # Priority color
                    priority_color = {
                        'High': '#DC2626',
                        'Medium': '#F59E0B',
                        'Low': '#10B981'
                    }.get(rec_priority, '#6B7280')
                    
                    rec_data = [[
                        Paragraph(f'<b>{i}. {rec_title}</b>', subheading_style),
                        Paragraph(rec_desc, normal_style),
                        Paragraph(f'<font size="8"><b>Priority:</b> {rec_priority} | <b>Impact:</b> {rec_impact} | <b>Effort:</b> {rec_effort}</font>', 
                                 ParagraphStyle('MetaStyle', textColor=colors.HexColor('#6B7280')))
                    ]]
                    
                    rec_table = Table(rec_data, colWidths=[A4[0] - 120])
                    rec_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F9FAFB')),
                        ('LEFTPADDING', (0, 0), (-1, -1), 15),
                        ('RIGHTPADDING', (0, 0), (-1, -1), 15),
                        ('TOPPADDING', (0, 0), (-1, -1), 10),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                        ('LINEABOVE', (0, 0), (-1, 0), 3, colors.HexColor(priority_color)),
                        ('ROUNDEDCORNERS', [8, 8, 8, 8])
                    ]))
                    
                    elements.append(rec_table)
                    elements.append(Spacer(1, 0.15*inch))
            else:
                elements.append(Paragraph("No recommendations available", normal_style))
            
            elements.append(PageBreak())
            
            # Detailed Analysis Sections
            sections = [
                ('🎨 UX Analysis', 'ux_analysis', '#3B82F6'),
                ('🔍 SEO Analysis', 'seo_analysis', '#10B981'),
                ('⚡ Performance Analysis', 'performance_analysis', '#F59E0B'),
                ('📝 Content Analysis', 'content_analysis', '#EF4444')
            ]
            
            for section_title, section_key, section_color in sections:
                section_data = analysis_data.get(section_key, {})
                score = section_data.get('score', 0)
                
                # Section header with color
                section_heading = ParagraphStyle(
                    'SectionHeading',
                    parent=heading_style,
                    textColor=colors.HexColor(section_color),
                    backColor=colors.HexColor(section_color + '15')
                )
                elements.append(Paragraph(section_title, section_heading))
                elements.append(Paragraph(f'<b>Score: {score:.0f}/100</b>', subheading_style))
                
                # Issues
                elements.append(Paragraph("<b>⚠️ Issues Found:</b>", subheading_style))
                issues = section_data.get('issues', [])
                if issues:
                    for issue in issues[:10]:
                        elements.append(Paragraph(f'• {issue}', bullet_style))
                else:
                    elements.append(Paragraph("✓ No issues found", normal_style))
                
                elements.append(Spacer(1, 0.15*inch))
                
                # Recommendations
                elements.append(Paragraph("<b>💡 Recommendations:</b>", subheading_style))
                recs = section_data.get('recommendations', [])
                if recs:
                    for rec in recs[:10]:
                        elements.append(Paragraph(f'• {rec}', bullet_style))
                else:
                    elements.append(Paragraph("No recommendations", normal_style))
                
                elements.append(Spacer(1, 0.3*inch))
            
            # Build PDF with page numbers
            print(f"📄 Building PDF document...")
            doc.build(elements, onFirstPage=self._add_page_number, onLaterPages=self._add_page_number)
            print(f"✅ PDF created successfully: {output_path}")
            
            return output_path
            
        except Exception as e:
            print(f"❌ PDF generation failed: {e}")
            import traceback
            traceback.print_exc()
            raise
    
    def _get_score_color(self, score: float) -> str:
        """Get color based on score"""
        if score >= 80:
            return '#10B981'  # Green
        elif score >= 60:
            return '#F59E0B'  # Yellow
        elif score >= 40:
            return '#F97316'  # Orange
        else:
            return '#EF4444'  # Red
