from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
from reportlab.pdfgen import canvas
from datetime import datetime
from typing import Dict
import os
import re
import html


class PDFService:
    """Service for generating PDF reports"""
    
    def __init__(self):
        self.output_dir = "app/static/pdfs"
        os.makedirs(self.output_dir, exist_ok=True)
        
        # Professional color palette with high contrast
        self.colors = {
            'primary': colors.HexColor('#1E40AF'),      # Deep Blue
            'primary_light': colors.HexColor('#3B82F6'), # Light Blue
            'secondary': colors.HexColor('#0F172A'),    # Dark Navy
            'accent': colors.HexColor('#6366F1'),       # Indigo
            'success': colors.HexColor('#059669'),      # Green
            'warning': colors.HexColor('#D97706'),      # Amber
            'danger': colors.HexColor('#DC2626'),       # Red
            'gray_dark': colors.HexColor('#374151'),    # Dark Gray
            'gray_medium': colors.HexColor('#6B7280'),  # Medium Gray
            'gray_light': colors.HexColor('#F3F4F6'),   # Light Gray
            'white': colors.white,
            'bg_blue': colors.HexColor('#EFF6FF'),      # Light Blue BG
            'bg_green': colors.HexColor('#ECFDF5'),     # Light Green BG
            'bg_yellow': colors.HexColor('#FFFBEB'),    # Light Yellow BG
            'bg_red': colors.HexColor('#FEF2F2'),       # Light Red BG
        }
    
    def _add_page_number(self, canvas, doc):
        """Add page numbers and footer to each page"""
        canvas.saveState()
        
        # Footer line
        canvas.setStrokeColor(self.colors['gray_light'])
        canvas.setLineWidth(1)
        canvas.line(50, 50, A4[0] - 50, 50)
        
        # Page number
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(self.colors['gray_medium'])
        canvas.drawRightString(A4[0] - 50, 35, text)
        
        # Footer text
        canvas.setFillColor(self.colors['gray_medium'])
        canvas.drawString(50, 35, "Generated by WebAnalyzer AI")
        
        # Website URL on right
        canvas.setFillColor(self.colors['primary'])
        canvas.drawRightString(A4[0] - 50, 20, "www.webanalyzer.ai")
        
        canvas.restoreState()
    
    def _sanitize_text(self, text: str) -> str:
        """Sanitize text for PDF - remove problematic HTML, links, and emojis"""
        if not text:
            return ""
        
        # Remove HTML anchor tags with href attributes (especially #anchors)
        text = re.sub(r'<a\s+[^>]*href=["\']#[^"\']*["\'][^>]*>(.*?)</a>', r'\1', text, flags=re.IGNORECASE)
        text = re.sub(r'<a\s+[^>]*href=["\'][^"\']*["\'][^>]*>(.*?)</a>', r'\1', text, flags=re.IGNORECASE)
        
        # Remove other problematic HTML tags but keep content
        text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.IGNORECASE | re.DOTALL)
        text = re.sub(r'<style[^>]*>.*?</style>', '', text, flags=re.IGNORECASE | re.DOTALL)
        
        # Remove emojis (Unicode emoji ranges)
        emoji_pattern = re.compile(
            "["
            "\U0001F600-\U0001F64F"  # emoticons
            "\U0001F300-\U0001F5FF"  # symbols & pictographs
            "\U0001F680-\U0001F6FF"  # transport & map symbols
            "\U0001F1E0-\U0001F1FF"  # flags (iOS)
            "\U00002702-\U000027B0"  # dingbats
            "\U000024C2-\U0001F251"  # enclosed characters
            "\U0001F900-\U0001F9FF"  # supplemental symbols
            "\U0001FA00-\U0001FA6F"  # chess symbols
            "\U00002600-\U000026FF"  # misc symbols
            "\U00002700-\U000027BF"  # dingbats
            "]+",
            flags=re.UNICODE
        )
        text = emoji_pattern.sub('', text)
        
        # Escape special characters for XML/HTML
        text = html.escape(text, quote=False)
        
        # Remove any remaining anchor references
        text = text.replace('href="#', 'href="')
        text = re.sub(r'href="#[^"]*"', '', text)
        
        return text.strip()
    async def generate_report(self, analysis_data: Dict) -> str:
        """Generate PDF report from analysis data"""
        try:
            filename = f"analysis_{analysis_data['id']}.pdf"
            output_path = os.path.join(self.output_dir, filename)
            
            print(f"📄 Creating enhanced PDF at: {output_path}")
            
            doc = SimpleDocTemplate(
                output_path,
                pagesize=A4,
                rightMargin=50,
                leftMargin=50,
                topMargin=60,
                bottomMargin=70
            )
            
            elements = []
            styles = getSampleStyleSheet()
            
            # Custom styles with better contrast
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=32,
                textColor=self.colors['white'],
                spaceAfter=10,
                alignment=TA_CENTER,
                fontName='Helvetica-Bold',
                leading=38
            )
            
            subtitle_style = ParagraphStyle(
                'Subtitle',
                parent=styles['Normal'],
                fontSize=11,
                textColor=self.colors['gray_dark'],
                alignment=TA_CENTER,
                spaceAfter=5,
                fontName='Helvetica'
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=20,
                textColor=self.colors['primary'],
                spaceAfter=15,
                spaceBefore=20,
                fontName='Helvetica-Bold'
            )
            
            subheading_style = ParagraphStyle(
                'CustomSubHeading',
                parent=styles['Heading3'],
                fontSize=14,
                textColor=self.colors['secondary'],
                spaceAfter=10,
                spaceBefore=12,
                fontName='Helvetica-Bold'
            )
            
            normal_style = ParagraphStyle(
                'CustomNormal',
                parent=styles['Normal'],
                fontSize=10,
                leading=16,
                alignment=TA_LEFT,
                textColor=self.colors['gray_dark'],
                fontName='Helvetica'
            )
            
            bullet_style = ParagraphStyle(
                'BulletStyle',
                parent=normal_style,
                leftIndent=20,
                bulletIndent=10,
                spaceAfter=6
            )
            
            # Header
            header_data = [[Paragraph("WEBSITE ANALYSIS REPORT", title_style)]]
            header_table = Table(header_data, colWidths=[A4[0] - 100])
            header_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), self.colors['primary']),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('TOPPADDING', (0, 0), (-1, -1), 25),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 25),
                ('ROUNDEDCORNERS', [12, 12, 12, 12])
            ]))
            elements.append(header_table)
            elements.append(Spacer(1, 0.25*inch))
            
            # Website info
            info_data = [[
                Paragraph(f"<b>Website:</b> {analysis_data.get('website_url', '')}", subtitle_style),
                Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", subtitle_style)
            ]]
            info_table = Table(info_data, colWidths=[3.5*inch, 3*inch])
            info_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), self.colors['bg_blue']),
                ('ALIGN', (0, 0), (0, 0), 'LEFT'),
                ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
                ('TOPPADDING', (0, 0), (-1, -1), 12),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('LEFTPADDING', (0, 0), (-1, -1), 15),
                ('RIGHTPADDING', (0, 0), (-1, -1), 15),
                ('ROUNDEDCORNERS', [8, 8, 8, 8])
            ]))
            elements.append(info_table)
            elements.append(Spacer(1, 0.35*inch))
            
            # Overall Score
            overall_score = analysis_data.get('overall_score', 0)
            score_color = self._get_score_color(overall_score)
            
            score_data = [
                [Paragraph(f'<font size="56" color="{score_color}"><b>{overall_score:.0f}</b></font>', 
                         ParagraphStyle('ScoreStyle', alignment=TA_CENTER))],
                [Paragraph('<font size="13" color="#6B7280"><b>Overall Score</b></font>', 
                         ParagraphStyle('ScoreLabelStyle', alignment=TA_CENTER))]
            ]
            
            score_table = Table(score_data, colWidths=[2.2*inch], rowHeights=[1*inch, 0.35*inch])
            score_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), self.colors['white']),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('BOX', (0, 0), (-1, -1), 3, colors.HexColor(score_color)),
                ('ROUNDEDCORNERS', [15, 15, 15, 15]),
                ('TOPPADDING', (0, 0), (-1, -1), 15),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 15)
            ]))
            
            score_wrapper = Table([[score_table]], colWidths=[A4[0] - 100])
            score_wrapper.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE')
            ]))
            elements.append(score_wrapper)
            elements.append(Spacer(1, 0.35*inch))
            
            # Score Breakdown
            ux_score = analysis_data.get('ux_analysis', {}).get('score', 0)
            seo_score = analysis_data.get('seo_analysis', {}).get('score', 0)
            perf_score = analysis_data.get('performance_analysis', {}).get('score', 0)
            content_score = analysis_data.get('content_analysis', {}).get('score', 0)
            
            score_breakdown = [
                [
                    Paragraph('<b>UX Score</b>', ParagraphStyle('', fontSize=11, alignment=TA_CENTER, textColor=self.colors['gray_dark'])),
                    Paragraph('<b>SEO Score</b>', ParagraphStyle('', fontSize=11, alignment=TA_CENTER, textColor=self.colors['gray_dark'])),
                    Paragraph('<b>Performance</b>', ParagraphStyle('', fontSize=11, alignment=TA_CENTER, textColor=self.colors['gray_dark'])),
                    Paragraph('<b>Content</b>', ParagraphStyle('', fontSize=11, alignment=TA_CENTER, textColor=self.colors['gray_dark']))
                ],
                [
                    Paragraph(f'<font size="28" color="{self._get_score_color(ux_score)}"><b>{ux_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="28" color="{self._get_score_color(seo_score)}"><b>{seo_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="28" color="{self._get_score_color(perf_score)}"><b>{perf_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER)),
                    Paragraph(f'<font size="28" color="{self._get_score_color(content_score)}"><b>{content_score:.0f}</b></font>', 
                             ParagraphStyle('', alignment=TA_CENTER))
                ]
            ]
            
            breakdown_table = Table(score_breakdown, colWidths=[1.5*inch] * 4, rowHeights=[0.35*inch, 0.7*inch])
            breakdown_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.colors['white']),
                ('BACKGROUND', (0, 1), (0, 1), self.colors['bg_blue']),
                ('BACKGROUND', (1, 1), (1, 1), self.colors['bg_green']),
                ('BACKGROUND', (2, 1), (2, 1), self.colors['bg_yellow']),
                ('BACKGROUND', (3, 1), (3, 1), self.colors['bg_red']),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                ('TOPPADDING', (0, 1), (-1, -1), 15),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 15),
                ('BOX', (0, 0), (-1, -1), 1.5, self.colors['gray_light']),
                ('INNERGRID', (0, 0), (-1, -1), 1.5, self.colors['white']),
                ('ROUNDEDCORNERS', [10, 10, 10, 10])
            ]))
            
            # Center the breakdown table
            breakdown_wrapper = Table([[breakdown_table]], colWidths=[A4[0] - 100])
            breakdown_wrapper.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE')
            ]))
            
            elements.append(breakdown_wrapper)
            elements.append(Spacer(1, 0.4*inch))
            
            # Executive Summary
            elements.append(Paragraph("Executive Summary", heading_style))
            elements.append(HRFlowable(width="100%", thickness=2, color=self.colors['primary_light'], spaceBefore=5, spaceAfter=15))
            
            summary_text = analysis_data.get('ai_summary', 'No summary available')
            summary_text = summary_text.replace('**', '').replace('##', '').replace('###', '').replace('*', '')
            
            for para in summary_text.split('\n\n'):
                if para.strip():
                    # Sanitize each paragraph
                    sanitized_para = self._sanitize_text(para.strip())
                    elements.append(Paragraph(sanitized_para, normal_style))
                    elements.append(Spacer(1, 0.12*inch))
            
            elements.append(Spacer(1, 0.25*inch))
            
            # Priority Recommendations
            elements.append(Paragraph("Priority Recommendations", heading_style))
            elements.append(HRFlowable(width="100%", thickness=2, color=self.colors['primary_light'], spaceBefore=5, spaceAfter=15))
            
            recommendations = analysis_data.get('priority_recommendations', [])
            
            if recommendations:
                for i, rec in enumerate(recommendations[:5], 1):
                    priority_colors = {
                        'High': (self.colors['danger'], self.colors['bg_red']),
                        'Medium': (self.colors['warning'], self.colors['bg_yellow']),
                        'Low': (self.colors['success'], self.colors['bg_green'])
                    }
                    border_color, bg_color = priority_colors.get(rec.get('priority', 'N/A'), (self.colors['gray_medium'], self.colors['gray_light']))
                    
                    # Sanitize recommendation text
                    rec_title = self._sanitize_text(str(rec.get("title", "")))
                    rec_desc = self._sanitize_text(str(rec.get('description', '')))
                    
                    rec_content = [
                        [Paragraph(f'<b>{i}. {rec_title}</b>', 
                                  ParagraphStyle('RecTitle', fontSize=13, textColor=self.colors['secondary'], fontName='Helvetica-Bold'))],
                        [Paragraph(rec_desc, normal_style)],
                        [Paragraph(f'<font size="9" color="#6B7280"><b>Priority:</b> {rec.get("priority", "N/A")} | <b>Impact:</b> {rec.get("impact", "N/A")} | <b>Effort:</b> {rec.get("effort", "N/A")}</font>', 
                                  ParagraphStyle('RecMeta'))]
                    ]
                    
                    rec_table = Table(rec_content, colWidths=[A4[0] - 120])
                    rec_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, -1), bg_color),
                        ('LEFTPADDING', (0, 0), (-1, -1), 15),
                        ('RIGHTPADDING', (0, 0), (-1, -1), 15),
                        ('TOPPADDING', (0, 0), (-1, -1), 12),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                        ('LINEABOVE', (0, 0), (-1, 0), 4, border_color),
                        ('ROUNDEDCORNERS', [8, 8, 8, 8])
                    ]))
                    
                    elements.append(rec_table)
                    elements.append(Spacer(1, 0.18*inch))
            
            elements.append(PageBreak())
            
            # Detailed Analysis Sections
            sections = [
                ('UX Analysis', 'ux_analysis', self.colors['primary'], self.colors['bg_blue']),
                ('SEO Analysis', 'seo_analysis', self.colors['success'], self.colors['bg_green']),
                ('Performance Analysis', 'performance_analysis', self.colors['warning'], self.colors['bg_yellow']),
                ('Content Analysis', 'content_analysis', self.colors['danger'], self.colors['bg_red'])
            ]
            
            for section_title, section_key, section_color, section_bg in sections:
                section_data = analysis_data.get(section_key, {})
                score = section_data.get('score', 0)
                
                # Create section content as a group to keep together
                section_elements = []
                
                section_elements.append(Paragraph(section_title, ParagraphStyle('SectionHeading', parent=heading_style, textColor=section_color)))
                section_elements.append(HRFlowable(width="100%", thickness=2, color=section_color, spaceBefore=5, spaceAfter=10))
                section_elements.append(Paragraph(f'<b>Score: <font color="{self._get_score_color(score)}">{score:.0f}/100</font></b>', 
                                        ParagraphStyle('ScoreBadge', fontSize=12, textColor=self.colors['gray_dark'])))
                section_elements.append(Spacer(1, 0.15*inch))
                
                # Issues section
                issues_elements = []
                issues_elements.append(Paragraph("<b>Issues Found:</b>", subheading_style))
                issues = section_data.get('issues', [])
                if issues:
                    for issue in issues[:10]:
                        # Sanitize issue text to remove problematic HTML/links
                        sanitized_issue = self._sanitize_text(str(issue))
                        issues_elements.append(Paragraph(f'• {sanitized_issue}', bullet_style))
                else:
                    issues_elements.append(Paragraph("No issues found", 
                                            ParagraphStyle('NoIssues', parent=normal_style, textColor=self.colors['success'])))
                
                # Keep issues heading with at least first 2 items
                section_elements.append(KeepTogether(issues_elements[:min(3, len(issues_elements))]))
                if len(issues_elements) > 3:
                    section_elements.extend(issues_elements[3:])
                
                section_elements.append(Spacer(1, 0.18*inch))
                
                # Recommendations section
                recs_elements = []
                recs_elements.append(Paragraph("<b>Recommendations:</b>", subheading_style))
                
                recs = section_data.get('recommendations', [])
                if recs:
                    for rec in recs[:10]:
                        # Sanitize recommendation text to remove problematic HTML/links
                        sanitized_rec = self._sanitize_text(str(rec))
                        recs_elements.append(Paragraph(f'• {sanitized_rec}', bullet_style))
                else:
                    recs_elements.append(Paragraph("No recommendations", normal_style))
                
                # Keep recommendations heading with at least first 2 items
                section_elements.append(KeepTogether(recs_elements[:min(3, len(recs_elements))]))
                if len(recs_elements) > 3:
                    section_elements.extend(recs_elements[3:])
                
                # Add all section elements
                elements.extend(section_elements)
                
                elements.append(Spacer(1, 0.35*inch))
            
            print(f"📄 Building PDF document...")
            doc.build(elements, onFirstPage=self._add_page_number, onLaterPages=self._add_page_number)
            print(f"✅ PDF created successfully: {output_path}")
            
            return output_path
            
        except Exception as e:
            print(f"❌ PDF generation failed: {e}")
            import traceback
            traceback.print_exc()
            raise
    
    def _get_score_color(self, score: float) -> str:
        """Get color based on score with high contrast"""
        if score >= 80:
            return '#059669'  # Green
        elif score >= 60:
            return '#D97706'  # Amber
        elif score >= 40:
            return '#F59E0B'  # Orange
        else:
            return '#DC2626'  # Red
